language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  
addons:
  sonarcloud:
    organization: "test" # the key of the org you chose at step #3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update -qq

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php -n composer.phar install --dev --verbose

script: 
  - phpunit
  - sonar-scanner
